steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - builds
  - submit 
  - --tag=gcr.io/$PROJECT_ID/$REPO_NAME

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - $REPO_NAME
    - --image=gcr.io/$PROJECT_ID/$REPO_NAME
    - --set-env-vars=NAME=${_NAME}
    - --platform=managed
    - --region=us-central1
    - --allow-unauthenticated